# MPLAB IDE generated this makefile for use with GNU make.
# Project: MotorTester.mcp
# Date: Sat Nov 15 19:58:21 2008

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

MotorTester.cod : 
	$(AS) /q /p16F88 "MotorTester.asm" /l"MotorTester.lst" /e"MotorTester.err" /d__DEBUG=1

clean : 
	$(RM) "MotorTester.cod" "MotorTester.hex" "MotorTester.err" "MotorTester.lst"

